package com.jshooting.forms;

import static com.jshooting.forms.MissMarksDialogTargetType.LYING;
import static com.jshooting.forms.MissMarksDialogTargetType.STANDING;
import java.awt.Window;

/**
 * Диалог редактирования отметок промахов
 *
 * @author pgalex
 */
public class EditMissMarksDialog extends javax.swing.JDialog
{
	/**
	 * Создать диалог
	 *
	 * @param parentWindow родительское окно
	 * @param modalityType modality type диалога
	 * @param targetType тип мишени. Должно быть не null
	 * @throws IllegalArgumentException targetType is null
	 */
	public EditMissMarksDialog(Window parentWindow, ModalityType modalityType, MissMarksDialogTargetType targetType) throws IllegalArgumentException
	{
		super(parentWindow, modalityType);
		if (targetType == null)
		{
			throw new IllegalArgumentException("targetType is null");
		}

		initComponents();

		setTitleByTargetType(targetType);
		setTargetImageByTargetType(targetType);
	}

	/**
	 * Установить заголовок диалога по типу мишени
	 *
	 * @param targetType тип мишени. Должно быть не null
	 * @throws IllegalArgumentException targetType is null
	 */
	private void setTitleByTargetType(MissMarksDialogTargetType targetType) throws IllegalArgumentException
	{
		if (targetType == null)
		{
			throw new IllegalArgumentException("targetType is null");
		}

		switch (targetType)
		{
			case LYING:
				setTitle("Отметки промахов лежа");
				break;
			case STANDING:
				setTitle("Отметки промахов стоя");
				break;
			default:
				throw new NullPointerException("unknown targetType value");
		}
	}

	/**
	 * Установить изображение мишени по типу мишени
	 *
	 * @param targetType тип мишени. Должно быть не null
	 * @throws IllegalArgumentException targetType is null
	 */
	private void setTargetImageByTargetType(MissMarksDialogTargetType targetType) throws IllegalArgumentException
	{
		if (targetType == null)
		{
			throw new IllegalArgumentException("targetType is null");
		}

		switch (targetType)
		{
			case LYING:
				jLabelTargetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jshooting/resources/мишеньЛежа.png")));
				break;
			case STANDING:
				jLabelTargetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jshooting/resources/мишеньСтоя.png")));
				break;
			default:
				throw new NullPointerException("unknown targetType value");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabelTargetImage = new javax.swing.JLabel();
    jButtonClearAllMarks = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    jLabelTargetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jshooting/resources/мишеньЛежа.png"))); // NOI18N
    jLabelTargetImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jButtonClearAllMarks.setText("Стереть все");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(jLabelTargetImage)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jButtonClearAllMarks)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jLabelTargetImage)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jButtonClearAllMarks))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonClearAllMarks;
  private javax.swing.JLabel jLabelTargetImage;
  // End of variables declaration//GEN-END:variables
}
