package com.jshooting.forms;

import com.jshooting.shootingDatabase.PlacesTable;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Window;
import javax.swing.DefaultCellEditor;
import javax.swing.table.TableColumn;

/**
 * Dialog for editing places
 *
 * @author pgalex
 */
public class EditPlacesDialog extends javax.swing.JDialog
{
	/**
	 * Table model of places table
	 */
	private PlacesTableModel placesTableModel;

	/**
	 * Creates new dialog
	 *
	 * @param parentWindow parent window
	 * @param modalityType modality type of dialog
	 * @param placesTable table of places
	 * @throws IllegalArgumentException placesTable is null
	 */
	public EditPlacesDialog(Window parentWindow, ModalityType modalityType, PlacesTable placesTable) throws IllegalArgumentException
	{
		super(parentWindow, modalityType);

		if (placesTable == null)
		{
			throw new IllegalArgumentException("placesTable is null");
		}

		placesTableModel = new PlacesTableModel(placesTable);

		initComponents();

		TableColumn beginDateColumn = jTablePlaces.getColumnModel().getColumn(PlacesTableModel.BEGIN_DATE_COLUMN_INDEX);
		beginDateColumn.setCellEditor(new DefaultCellEditor(new JTextFieldDateEditor(null, null, '-')));

		TableColumn endDateColumn = jTablePlaces.getColumnModel().getColumn(PlacesTableModel.END_DATE_COLUMN_INDEX);
		endDateColumn.setCellEditor(new DefaultCellEditor(new JTextFieldDateEditor(null, null, '-')));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTablePlaces = new javax.swing.JTable();
    jButtonAddPlace = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("УТС");

    jTablePlaces.setModel(placesTableModel);
    jTablePlaces.setRowHeight(24);
    jScrollPane1.setViewportView(jTablePlaces);

    jButtonAddPlace.setText("Добавить");
    jButtonAddPlace.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAddPlaceActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jButtonAddPlace)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jButtonAddPlace)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonAddPlaceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddPlaceActionPerformed
  {//GEN-HEADEREND:event_jButtonAddPlaceActionPerformed
		placesTableModel.addNewPlace();
  }//GEN-LAST:event_jButtonAddPlaceActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAddPlace;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTablePlaces;
  // End of variables declaration//GEN-END:variables
}
