package com.jshooting.forms;

import static com.jshooting.forms.MissMarksDialogTargetType.LYING;
import static com.jshooting.forms.MissMarksDialogTargetType.STANDING;
import com.jshooting.model.MissMarksArray;
import java.awt.Graphics;
import java.awt.Window;
import java.awt.event.MouseEvent;
import java.awt.geom.Point2D;
import javax.swing.ImageIcon;

/**
 * Диалог редактирования отметок промахов
 *
 * @author pgalex
 */
public class EditMissMarksDialog extends javax.swing.JDialog implements MissMarksTargetPanelPaintDelegate
{
	private static ImageIcon MISS_MARKS_IMAGE = new javax.swing.ImageIcon(EditMissMarksDialog.class.getResource("/com/jshooting/resources/отметкаПромаха.png"));
	private MissMarksArray editingMarksArray;

	/**
	 * Создать диалог
	 *
	 * @param parentWindow родительское окно
	 * @param modalityType modality type диалога
	 * @param targetType тип мишени. Должно быть не null
	 * @param missMarksToEdit редактируемые отметки промахов. Должно быть не null
	 * @throws IllegalArgumentException targetType is null
	 */
	public EditMissMarksDialog(Window parentWindow, ModalityType modalityType, MissMarksDialogTargetType targetType,
					MissMarksArray missMarksToEdit) throws IllegalArgumentException
	{
		super(parentWindow, modalityType);
		if (targetType == null)
		{
			throw new IllegalArgumentException("targetType is null");
		}
		if (missMarksToEdit == null)
		{
			throw new IllegalArgumentException("missMarksToEdit is null");
		}
		editingMarksArray = missMarksToEdit;

		initComponents();

		setTitleByTargetType(targetType);
		setTargetImageByTargetType(targetType);
	}

	/**
	 * Установить заголовок диалога по типу мишени
	 *
	 * @param targetType тип мишени. Должно быть не null
	 * @throws IllegalArgumentException targetType is null
	 */
	private void setTitleByTargetType(MissMarksDialogTargetType targetType) throws IllegalArgumentException
	{
		if (targetType == null)
		{
			throw new IllegalArgumentException("targetType is null");
		}

		switch (targetType)
		{
			case LYING:
				setTitle("Отметки промахов лежа");
				break;
			case STANDING:
				setTitle("Отметки промахов стоя");
				break;
			default:
				throw new NullPointerException("unknown targetType value");
		}
	}

	/**
	 * Установить изображение мишени по типу мишени
	 *
	 * @param targetType тип мишени. Должно быть не null
	 * @throws IllegalArgumentException targetType is null
	 */
	private void setTargetImageByTargetType(MissMarksDialogTargetType targetType) throws IllegalArgumentException
	{
		if (targetType == null)
		{
			throw new IllegalArgumentException("targetType is null");
		}

		switch (targetType)
		{
			case LYING:
				jLabelTargetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jshooting/resources/мишеньЛежа.png")));
				break;
			case STANDING:
				jLabelTargetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jshooting/resources/мишеньСтоя.png")));
				break;
			default:
				throw new NullPointerException("unknown targetType value");
		}
	}

	@Override
	public void paintOnTargetPanel(Graphics panelGraphics)
	{
		for (int i = 0; i < editingMarksArray.count(); i++)
		{
			Point2D missMark = editingMarksArray.get(i);

			panelGraphics.drawImage(MISS_MARKS_IMAGE.getImage(),
							(int) (missMark.getX() - MISS_MARKS_IMAGE.getIconWidth() / 2),
							(int) (missMark.getY() - MISS_MARKS_IMAGE.getIconHeight() / 2), null);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabelTargetImage = new MissMarksTargetLabel(this);
    jButtonClearAllMarks = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    jLabelTargetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jshooting/resources/мишеньЛежа.png"))); // NOI18N
    jLabelTargetImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabelTargetImage.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        jLabelTargetImageMouseReleased(evt);
      }
    });

    jButtonClearAllMarks.setText("Стереть все");
    jButtonClearAllMarks.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonClearAllMarksActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("ЛКМ - установить точку; ПКМ - удалить точку");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(jLabelTargetImage)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jButtonClearAllMarks)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jLabelTargetImage)
          .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jButtonClearAllMarks)))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jLabel1))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jLabelTargetImageMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelTargetImageMouseReleased
  {//GEN-HEADEREND:event_jLabelTargetImageMouseReleased
		if (evt.getButton() == MouseEvent.BUTTON1)
		{
			editingMarksArray.add(new Point2D.Double(evt.getX(), evt.getY()));
		}
		else
		{
			editingMarksArray.deleteFirstMissMarkAtCoordinates(evt.getX(), evt.getY());
		}
		jLabelTargetImage.repaint();
  }//GEN-LAST:event_jLabelTargetImageMouseReleased

  private void jButtonClearAllMarksActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonClearAllMarksActionPerformed
  {//GEN-HEADEREND:event_jButtonClearAllMarksActionPerformed
		editingMarksArray.clear();
		jLabelTargetImage.repaint();
  }//GEN-LAST:event_jButtonClearAllMarksActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonClearAllMarks;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabelTargetImage;
  // End of variables declaration//GEN-END:variables
}
