package com.jshooting.forms;

import com.jshooting.componentsHighlighting.ComponentsHighlighter;
import com.jshooting.logics.ShootingLogicsFactory;
import java.awt.Window;

/**
 * Training methods editing dialog
 *
 * @author pgalex
 */
public class EditTrainingMethodsDialog extends javax.swing.JDialog
{
	/**
	 * Components highlighter
	 */
	private ComponentsHighlighter componentsHighlighter;
	/**
	 * Table model for training methods table
	 */
	private TrainingMethodsTableModel trainingMethodsTableModel;

	/**
	 * Create new dialog
	 *
	 * @param parentWindow parent window
	 * @param modalityType modality type of dialog
	 * @param logicsFactory logics fatory. Must be not null
	 * @throws IllegalArgumentException logicsFactory is null
	 */
	public EditTrainingMethodsDialog(Window parentWindow, ModalityType modalityType,
					ShootingLogicsFactory logicsFactory) throws IllegalArgumentException
	{
		super(parentWindow, modalityType);

		if (logicsFactory == null)
		{
			throw new IllegalArgumentException("logicsFactory is null");
		}

		trainingMethodsTableModel = new TrainingMethodsTableModel(logicsFactory);
		componentsHighlighter = new ComponentsHighlighter();

		initComponents();

		updateHighlighting();
	}

	private void updateHighlighting()
	{
		if (jTableTrainingMethods.getRowCount() == 0)
		{
			componentsHighlighter.startComponentHightlighing(jButtonAddTrainingMethod, HighlightingConstants.GOOD_HIGHLIGHT_COLOR, HighlightingConstants.BLINKING_TIME);
		}
		else
		{
			componentsHighlighter.stopComponentHighlighting(jButtonAddTrainingMethod);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTableTrainingMethods = new javax.swing.JTable();
    jButtonAddTrainingMethod = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Средства");

    jTableTrainingMethods.setModel(trainingMethodsTableModel);
    jTableTrainingMethods.setRowHeight(24);
    jScrollPane1.setViewportView(jTableTrainingMethods);

    jButtonAddTrainingMethod.setText("Добавить");
    jButtonAddTrainingMethod.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAddTrainingMethodActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jButtonAddTrainingMethod)
        .addContainerGap(289, Short.MAX_VALUE))
      .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jButtonAddTrainingMethod)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonAddTrainingMethodActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddTrainingMethodActionPerformed
  {//GEN-HEADEREND:event_jButtonAddTrainingMethodActionPerformed
		trainingMethodsTableModel.addNewTrainingMethod();
		if (jTableTrainingMethods.getRowCount() > 0)
		{
			jTableTrainingMethods.setRowSelectionInterval(jTableTrainingMethods.getRowCount() - 1, jTableTrainingMethods.getRowCount() - 1);
			jTableTrainingMethods.editCellAt(jTableTrainingMethods.getRowCount() - 1, TrainingMethodsTableModel.NAME_COLUMN_INDEX);
			jTableTrainingMethods.requestFocus();
		}

		updateHighlighting();
  }//GEN-LAST:event_jButtonAddTrainingMethodActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAddTrainingMethod;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableTrainingMethods;
  // End of variables declaration//GEN-END:variables
}
