/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jshooting.forms;

/**
 *
 * @author pgalex
 */
public class EditSportsmansDialog extends javax.swing.JDialog
{
	/**
	 * Creates new form EditSportsmansDialog
	 */
	public EditSportsmansDialog(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTableSportsmans = new javax.swing.JTable();
    jComboBoxTeam = new javax.swing.JComboBox();
    jLabelTeam = new javax.swing.JLabel();
    jButtonAddSportsman = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jTableSportsmans.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {

      }
    ));
    jScrollPane1.setViewportView(jTableSportsmans);

    jComboBoxTeam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabelTeam.setText("Команда");

    jButtonAddSportsman.setText("Добавить");
    jButtonAddSportsman.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAddSportsmanActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .add(14, 14, 14)
        .add(jLabelTeam)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jComboBoxTeam, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jButtonAddSportsman)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jButtonAddSportsman)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jComboBoxTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jLabelTeam))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonAddSportsmanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddSportsmanActionPerformed
  {//GEN-HEADEREND:event_jButtonAddSportsmanActionPerformed
  }//GEN-LAST:event_jButtonAddSportsmanActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAddSportsman;
  private javax.swing.JComboBox jComboBoxTeam;
  private javax.swing.JLabel jLabelTeam;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableSportsmans;
  // End of variables declaration//GEN-END:variables
}
