/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jshooting.forms;

import java.awt.Window;
import java.util.Date;

/**
 * Shooting trainings filter setup dialog. Using to find which trainings need to
 * use
 *
 * @author pgalex
 */
public class ShootingTrainingsFilterDialog extends javax.swing.JDialog
{
	/**
	 * Is OK button was pressed
	 */
	private boolean okButtonPressed;

	/**
	 * Create new dialog
	 *
	 * @param parentWindow parent window
	 * @param modalityType modality type of dialog
	 */
	public ShootingTrainingsFilterDialog(Window parentWindow, ModalityType modalityType)
	{
		super(parentWindow, modalityType);

		okButtonPressed = false;

		initComponents();
		jDateChooserDateFrom.setDate(new Date());
		jDateChooserDateTo.setDate(new Date());
		setTitle("Фильтр");
	}

	/**
	 * Is OK button was pressed
	 *
	 * @return is OK button was pressed
	 */
	public boolean isOKButtonPressed()
	{
		return okButtonPressed;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanelSportsmans = new javax.swing.JPanel();
    jLabelTeam = new javax.swing.JLabel();
    jComboBoxTeams = new javax.swing.JComboBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    jListSportsmans = new javax.swing.JList();
    jPanelPeriod = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jDateChooserDateFrom = new com.toedter.calendar.JDateChooser();
    jLabel2 = new javax.swing.JLabel();
    jDateChooserDateTo = new com.toedter.calendar.JDateChooser();
    jPanelTrainingsType = new javax.swing.JPanel();
    jCheckBoxComplex = new javax.swing.JCheckBox();
    jCheckBoxShooting = new javax.swing.JCheckBox();
    jCheckBoxCompetition = new javax.swing.JCheckBox();
    jButtonOK = new javax.swing.JButton();
    jButtonCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    jPanelSportsmans.setBorder(javax.swing.BorderFactory.createTitledBorder("Спортсмены"));

    jLabelTeam.setText("Команда");

    jComboBoxTeams.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jComboBoxTeamsActionPerformed(evt);
      }
    });

    jListSportsmans.setModel(new javax.swing.AbstractListModel()
    {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "6", "7", "8", "9", "10", "11", "12" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(jListSportsmans);

    org.jdesktop.layout.GroupLayout jPanelSportsmansLayout = new org.jdesktop.layout.GroupLayout(jPanelSportsmans);
    jPanelSportsmans.setLayout(jPanelSportsmansLayout);
    jPanelSportsmansLayout.setHorizontalGroup(
      jPanelSportsmansLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanelSportsmansLayout.createSequentialGroup()
        .addContainerGap()
        .add(jPanelSportsmansLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jScrollPane1)
          .add(jPanelSportsmansLayout.createSequentialGroup()
            .add(jLabelTeam)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jComboBoxTeams, 0, 172, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanelSportsmansLayout.setVerticalGroup(
      jPanelSportsmansLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanelSportsmansLayout.createSequentialGroup()
        .add(jPanelSportsmansLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jComboBoxTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jLabelTeam))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanelPeriod.setBorder(javax.swing.BorderFactory.createTitledBorder("Период (включительно)"));

    jLabel1.setText("c");

    jLabel2.setText("по");

    org.jdesktop.layout.GroupLayout jPanelPeriodLayout = new org.jdesktop.layout.GroupLayout(jPanelPeriod);
    jPanelPeriod.setLayout(jPanelPeriodLayout);
    jPanelPeriodLayout.setHorizontalGroup(
      jPanelPeriodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanelPeriodLayout.createSequentialGroup()
        .addContainerGap()
        .add(jPanelPeriodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jLabel1)
          .add(jLabel2))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanelPeriodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jDateChooserDateTo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
          .add(jDateChooserDateFrom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanelPeriodLayout.setVerticalGroup(
      jPanelPeriodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanelPeriodLayout.createSequentialGroup()
        .add(jPanelPeriodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(jDateChooserDateFrom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanelPeriodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(jDateChooserDateTo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanelTrainingsType.setBorder(javax.swing.BorderFactory.createTitledBorder("Тип тренировки"));

    jCheckBoxComplex.setSelected(true);
    jCheckBoxComplex.setText("Комплексная");
    jCheckBoxComplex.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jCheckBoxComplexActionPerformed(evt);
      }
    });

    jCheckBoxShooting.setSelected(true);
    jCheckBoxShooting.setText("Стрелковая");
    jCheckBoxShooting.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jCheckBoxShootingActionPerformed(evt);
      }
    });

    jCheckBoxCompetition.setSelected(true);
    jCheckBoxCompetition.setText("Соревнование");

    org.jdesktop.layout.GroupLayout jPanelTrainingsTypeLayout = new org.jdesktop.layout.GroupLayout(jPanelTrainingsType);
    jPanelTrainingsType.setLayout(jPanelTrainingsTypeLayout);
    jPanelTrainingsTypeLayout.setHorizontalGroup(
      jPanelTrainingsTypeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanelTrainingsTypeLayout.createSequentialGroup()
        .addContainerGap()
        .add(jPanelTrainingsTypeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jCheckBoxComplex)
          .add(jCheckBoxShooting)
          .add(jCheckBoxCompetition))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanelTrainingsTypeLayout.setVerticalGroup(
      jPanelTrainingsTypeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanelTrainingsTypeLayout.createSequentialGroup()
        .add(jCheckBoxComplex)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jCheckBoxShooting)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jCheckBoxCompetition)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jButtonOK.setText("OK");
    jButtonOK.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonOKActionPerformed(evt);
      }
    });

    jButtonCancel.setText("Отмена");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(jPanelSportsmans, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanelPeriod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanelTrainingsType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(jButtonOK)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonCancel)))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanelTrainingsType, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPeriod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(jPanelSportsmans, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jButtonOK)
          .add(jButtonCancel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBoxTeamsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxTeamsActionPerformed
  {//GEN-HEADEREND:event_jComboBoxTeamsActionPerformed
  }//GEN-LAST:event_jComboBoxTeamsActionPerformed

  private void jCheckBoxComplexActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxComplexActionPerformed
  {//GEN-HEADEREND:event_jCheckBoxComplexActionPerformed
		// TODO add your handling code here:
  }//GEN-LAST:event_jCheckBoxComplexActionPerformed

  private void jCheckBoxShootingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxShootingActionPerformed
  {//GEN-HEADEREND:event_jCheckBoxShootingActionPerformed
		// TODO add your handling code here:
  }//GEN-LAST:event_jCheckBoxShootingActionPerformed

  private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOKActionPerformed
  {//GEN-HEADEREND:event_jButtonOKActionPerformed
		okButtonPressed = true;
  }//GEN-LAST:event_jButtonOKActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonCancel;
  private javax.swing.JButton jButtonOK;
  private javax.swing.JCheckBox jCheckBoxCompetition;
  private javax.swing.JCheckBox jCheckBoxComplex;
  private javax.swing.JCheckBox jCheckBoxShooting;
  private javax.swing.JComboBox jComboBoxTeams;
  private com.toedter.calendar.JDateChooser jDateChooserDateFrom;
  private com.toedter.calendar.JDateChooser jDateChooserDateTo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabelTeam;
  private javax.swing.JList jListSportsmans;
  private javax.swing.JPanel jPanelPeriod;
  private javax.swing.JPanel jPanelSportsmans;
  private javax.swing.JPanel jPanelTrainingsType;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
